name: Compile R code

on:
  push:
    branches:
      - main

jobs:
  compile_r_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile R code
        run: |
 
          pwd
          R CMD SHLIB test.R
          pwd
          ls -l
