name: Compile R Code

on:
  push:
    branches:
      - main

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Compile R code
        run: Rscript -e 'source("test.R")'

      # - name: Compile R code
      #   run: echo 'efh <- data.frame(cond = c("A", "A", "A", "A", "A", "A", "A", "A", "B", "B", "B", "B", "B", "B", "B"),test = c(0.71, 0.82, 0.82, 0.76, 0.76, 0.71, 0.71, 0.82, 0.65, 0.53, 0.88, 0.59, 0.76, 0.59, 0.65),msat = c(650, 710, 510, 590, 500, 730, 570, 780, 690, 710, 780, 690, 730, 700, 740))' > test.R
      #   run: Rscript -e 'source("test.R")'

      - name: Perform t-test
        run: Rscript -e 't_test <- t.test(test ~ cond, data = efh); print(t_test)'
