name: Compile R code

on:
  push:
    branches:
      - main

jobs:
  compile_r_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile R code
        run: |
          compiled_file=$(R CMD SHLIB test.R 2>&1 | grep -o "*.so")
          if [[ -z "$compiled_file" ]]; then
            echo "Error: Compilation failed"
            cat R CMD SHLIB test.R 2>&1
            exit 1
          fi
          echo "Compiled file: $compiled_file"

      - name: Run compiled code
        run: Rscript -e "dyn.load('$compiled_file'); my_function()"
