name: Compile R Script
 
on:
  push:
      paths:
        - 'migrated-sas-access-samples-master/**'
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.2'  # You can specify the desired R version here
    - name: Run R script
      run: Rscript migrated-sas-access-samples-master/*.R
